version: '3.4'

services:
  uniresolverdriverdidion:
    image: uniresolverdriverdidion
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+;
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
